### ISSUE TITLE
Package Issue

### ISSUE THREAD

**Issue by hassandraga** [webui-dev/go-webui#1]
`go install github.com/webui-dev/go-webui@latest`

```
go: downloading github.com/webui-dev/go-webui v0.1.0
go: github.com/webui-dev/go-webui@latest: module github.com/webui-dev/go-webui@latest found (v0.1.0), but does not contain package github.com/webui-dev/go-webui
```

**Comment by neroist** [comment]
Yeah, there isn't supposed to be an `src` directory in Golang packages ([see here](https://github.com/golang-standards/project-layout#directories-you-shouldnt-have)).

**Comment by AlbertShown** [comment]
`go install github.com/webui-dev/go-webui@latest`

```
go: downloading github.com/webui-dev/go-webui v0.1.0
go: github.com/webui-dev/go-webui@latest: module github.com/webui-dev/go-webui@latest found (v0.1.0), but does not contain package github.com/webui-dev/go-webui
```

I got the same error.

**Comment by neroist** [comment]
Yeah, I'm not sure why go keeps installing that version. @2.3.0.1 works for me.

**Comment by AlbertShown** [comment]
`go install github.com/webui-dev/go-webui@2.3.0.1`

```
go: downloading github.com/webui-dev/go-webui v0.0.0-20230516030851-d5cd38ca08af
package github.com/webui-dev/go-webui is not a main package
```

Strange!

**Comment by AlbertShown** [comment]
It does not work even with `go clean -cache -modcache`.
How did you install v2.3.0.1?

**Comment by neroist** [comment]
> `go install github.com/webui-dev/go-webui@2.3.0.1`
> 
> ```
> go: downloading github.com/webui-dev/go-webui v0.0.0-20230516030851-d5cd38ca08af
> package github.com/webui-dev/go-webui is not a main package
> ```
> 
> Strange!

I think thats just a warning? Even if i try to `go install` other packages it prints the same thing.

That or `go install` is only for main packages :P idk

**Comment by AlbertShown** [comment]
I'm sorry, guys. I deleted all the tags/releases in this repo. I was trying to fix the `v0.1.0` issue. But it is still not working.

**Comment by AlbertShown** [comment]
Sorry guys, I give up. I won't update this repo until someone figures out how to fix this.
Please, to make sure your fix is working, do this:

1. **_IMPORTANT:_** Use a clean new OS in a virtual machine or simply run a Windows Sandbox.
2. In the new, clean OS, install Go
3. Copy this simple TestMyLibrary example
4. Try your best to make it work using WebUI v2.3.0

[TestMyLibrary.zip](https://github.com/webui-dev/go-webui/files/11492324/TestMyLibrary.zip)

Thank you.

**Comment by AlbertShown** [comment]
Issue:
`go get github.com/webui-dev/go-webui@latest` will poll an old commit instead of the latest one.

**Comment by hassandraga** [comment]
The Go semantic versioning is quit different from other packages...

WebUI version right now is v2, so Go requires to create a folder called `v2`, this is to makes programs works even if we move in the future to WebUI v3 for example, so Go programs right now should import WebUI v2 using this link `github.com/webui-dev/go-webui/v2`, while in `github.com/webui-dev/go-webui` means mono version v1.

The `v0.1.0` you saw in your terminal is coming from here https://pkg.go.dev/github.com/webui-dev/go-webui. And to refresh it we can use https://sum.golang.org/lookup/github.com/webui-dev/go-webui@v2.3.0.

To install: `go get github.com/webui-dev/go-webui/v2@latest`
To import: `import "github.com/webui-dev/go-webui/v2"`

Don't use `go install`, because this command download and build... but `go get` means `install` like `apt install` on Linux... well, as I say, Go semantic versioning is weird. But it is what it is.

**Comment by AlbertShown** [comment]
It still does not work.

```
go clean -modcache
go get github.com/webui-dev/go-webui/v2@latest
go build
        main.go:3:8: no required module provides package github.com/webui-dev/go-webui/v2; to add it:
                go get github.com/webui-dev/go-webui/v2
```

**Comment by hassandraga** [comment]
Works with 2.4.0.
