### ISSUE TITLE
Prevent examples from being added to the go path

### ISSUE THREAD

**Issue by ttytm** [webui-dev/go-webui#21]
The current location of the examples is convenient for testing, as they use the go-webui package relative to their location. This makes it possible to execute them with local changes to the go-webui library files.

But it would be good to prevent the examples from being included when using `go get github.com/webui-dev/go-webui/v2/@<version>`. The examples are the largest path of the repo and they are not necessary to have them in the GOPATH of the package, so we don't need to pollute it. 

It would be possible by either storing them in the repository root. Then the example directory could be manually moved to the `v2/` directory for local development and testing. Or prefixing the examples directory with `_` should also work, so they would be stored in `v2/_examples`.

**Comment by hassandraga** [comment]
Moving to root probably is easier 👍

**Comment by ttytm** [comment]
Thanks for the input @hassandraga.

Gonna do so :+1:

I thought a rename would be easier if it would work. As it would not require moving the folder manually from the root to the v2 dir if one wants to run examples with local changes to the library.

According to this [SO post](https://stackoverflow.com/questions/57629849/stop-the-go-mod-tool-from-parsing-certain-directories) prefixing with an underscore should make Go tools ignore a folder. But this doesn't seem to be the case for `go get`. I tested the solution with the underscore prefix on a fork. The `_examples` directory is still added to the go path when using `go get`.

**Comment by hassandraga** [comment]
I guess there's no way to make `go get` skip cloning certain parts of the repository. It basically clones everything. But we can add `// +build ignore` at the top of every example file to be ignored in the WebUI compile and install process.

However, if you think renaming will work then we can do it 👍

**Comment by ttytm** [comment]
Moving it to the root is a fine solution. `go get` will just clone the module part of the package to the go path (where the `go.mod` for the library resides).
 
![Screenshot_20231020_021855](https://github.com/webui-dev/go-webui/assets/34311583/a5fd70af-1e1d-4b23-b52a-f1c6660aecc7)
