### ISSUE TITLE
looses window on 

### ISSUE THREAD

**Issue by noiseoverip** [webui-dev/go-webui#23]
On M1 Mac with Sonoma 14.2.1, it seems to fail to receive anything from the started browser window and exits. I thought it might be a firewall, but disabling it didn't help. Using v.2.4.1, go 1.21.5

```
[Core]          _webui_server_thread([1]) -> Waiting for first connection...
[Core]          _webui_server_thread([1]) -> Cleaning...
[Core]          _webui_free_port([57418])...
[Core]          _webui_free_port([50550])...
[Core]          _webui_server_thread([1]) -> Server stoped.

```

**Comment by ttytm** [comment]
To me it looks like you might not have included:
```html
<script src="webui.js"></script>
```

Can you re-test or share a code sample to have something reproducible?

**Comment by ttytm** [comment]
Gonna close due to a missing reproducible case and inactivity. Please don't hesitate to reach out if you encounter this issue again.
