### ISSUE TITLE
ERROR with CGO

### ISSUE THREAD

**Issue by Aukstkalnis** [webui-dev/go-webui#4]
Hello.

I followed build instructions but got this error with CGO:
[webui_test]$ go build
# webui_test
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: /tmp/go-link-1020940490/000001.o: in function `_cgo_2e88dd36e651_Cfunc_webui_decode':
/tmp/go-build/cgo-gcc-prolog:77: undefined reference to `webui_decode'
/usr/bin/ld: /tmp/go-link-1020940490/000001.o: in function `_cgo_2e88dd36e651_Cfunc_webui_encode':
/tmp/go-build/cgo-gcc-prolog:95: undefined reference to `webui_encode'
collect2: error: ld returned 1 exit status

The go version is v1.21.1
OS: fedora 38

Am I missing something?

**Comment by hassandraga** [comment]
This error is because Go-WebUI needs to be updated to the latest WebUI Lib.
We need to [copy this](https://github.com/webui-dev/webui/releases/tag/nightly) to [here](https://github.com/webui-dev/go-webui/tree/main/v2).
I will update it today.

**Comment by hassandraga** [comment]
I updated the repo. I test it locally, build and runs fine now. But I still have some issues with the Go package versioning...

**Comment by hassandraga** [comment]
https://sum.golang.org/lookup/github.com/webui-dev/go-webui@v2.4.0

```
not found: github.com/webui-dev/go-webui@v2.4.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/webui-dev/go-webui/v2")
```

Updating the [pkg.go.dev](https://pkg.go.dev/github.com/webui-dev/go-webui/v2) is not working for now... But the repo itself is ready to use.

**Comment by hassandraga** [comment]
[pkg.go.dev](https://pkg.go.dev/github.com/webui-dev/go-webui/v2) is updated to v2.4.0. Please try again `go get github.com/webui-dev/go-webui/v2`.

**Comment by Aukstkalnis** [comment]
Yes, it does work now. Thank you :)
