### ISSUE TITLE
setup.sh needs some additional quoting at line 48

### ISSUE THREAD

**Issue by rsdoiel** [webui-dev/go-webui#40]
### Description

I tried running the curl command to up a Go project to use go-webui. The `setup.sh` script failed. Running it through shellcheck I noticed a warning about line 48 `ln -s $webui_path $go_webui_path/webui` suggesting quoting.  I added the quotes and the script ran fine.  I think the line should be ...

```sh
ln -s "$webui_path" "$go_webui_path/webui"
```

All the best, Robert

### Expected Behavior

setup.sh should not fail to run properly.

### Reproduction Steps

run the Curl suggestion for go module usage on macOS version 14.5 (Sonoma) under Bash shell. Bash --version reports "GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.".

### Possible Solution

Change line 48 to have quoted shell variables.

### Version

The hash in go-webui is 5778f98  

### Environment Details (OS name, version, etc.)

```shell
Darwin 23.5.0 arm64
```

**Comment by ttytm** [comment]
Thanks for the report @rsdoiel. 

Good catch! It will be good to add the quotes. It will ensure things work as expected e.g. in case the paths contain spaces.

Do you want to submit a PR with that change?

**Comment by rsdoiel** [comment]
Sure. Let me give that a try. Thanks.
