### ISSUE TITLE
Use system GOPATH if env variable is not set

### ISSUE THREAD

**Issue by FredFoo** [webui-dev/go-webui#44]
### Description

When using the proposed command 

`sh -c "$(curl -fsSL https://raw.githubusercontent.com/webui-dev/go-webui/main/setup.sh)"`

I had an error because my GOPATH is not set, but the system configuration puts it not in $HOME/go, but somewhere else. 

### Use Case

Allow setup to work without need to assume gopath location

### Proposed Solution

Any locally configured gopath can easily be retrieved by calling 'go env GOPATH'.  Use go env to find the systems gopath instead of hard coded path.

### Implementation

- [ ] I may be able to implement the feature.
- [ ] It might incur a breaking change.

### Version

go-webui/v2@v2.4.3-0.20240711195955-8001a5e84f7d

### Environment Details (OS name, version, etc.)

```shell
Linux 6.6.54-2-MANJARO x86_64
go1.23.0 linux/amd64
```

**Comment by ttytm** [comment]
Thanks for the good report pointing that out
The linked PR should fix it.
